module TouRETS
  module Utilities
    
    # Convert a key value pair into a RETS formatted query string.
    # TODO: Take values that are arrays, ranges, or hashes, and convert those properly
    def hash_to_rets_query_string(hash)
      [].tap do |str|
        hash.each_pair do |k,v|
          val = value_map(v)
          str << "(#{k.to_s.camelize}=#{val})"
        end
      end.join(',')
    end
    
    # This takes a hash of search parameters, and modifies 
    # the hash to have the correct key types for the current RETS server
    def map_search_params(search_params)
      Hash[search_params.map {|k, v| [key_map[k], v] }]
    end
    
    
    # Giant Hash.
    # TODO: OPTIMIZE!!!! ZOMG! O_o
    # Maybe break this into a YAML file that will pick which keymap to use based on the current_connection?
    # I'm thinking maybe like a dictionary lookup. Figure out what each RETS server uses.
    # Also good to note that there are different data types, but they all are strings. 
    # We could figure out a way to convert to Integer, or DateTime objects, etc... depending.
    # All results are esentially just strings. The comments below indicate what the value type should be by how it's formatted
    
    def key_map
      {
        :id => 'sysid',
        :property_type  => 1 ,
        :approximate_acreage  => 2 ,
        :zip_code => 10 ,
        :statuschangedate => 18 ,
        :actual_close_date => 25 ,
        :la_name => 26 ,
        :dishwasher_inc => 30 ,
        :disposal_included => 31 ,
        :refrigerator_included => 33 ,
        :dryer_utilities => 34 ,
        :area => 37 ,
        :three_quarter_baths => 60 ,
        :full_baths => 61 ,
        :half_baths => 62 ,
        :baths_total => 63 ,
        :bath_downstairs_description => 64 ,
        :bedrooms => 68 ,
        :built_description => 72 ,
        :carport_description => 73 ,
        :carport => 74 ,
        :comp_days_on_market => 81 ,
        :contingency_desc => 84 ,
        :acceptance_date => 85 ,
        :cooling_fuel_description => 86 ,
        :county_name => 87 ,
        :second_bedroom_dimensions => 89 ,
        :third_bedroom_dimensions => 90 ,
        :fourth_bedroom_dimensions => 91 ,
        :dining_room_dimensions => 92 ,
        :family_room_dimensions => 93 ,
        :fifth_bedroom_dimensions => 94 ,
        :living_room_dimensions => 95 ,
        :master_bedroom_dimensions => 96 ,
        :fifth_bedroom_description => 97 ,
        :dom => 101 ,
        :entry_date => 104 ,
        :fence => 112 ,
        :fireplaces => 113 ,
        :converted_garage => 120 ,
        :garage => 122 ,
        :images => 129 ,
        :internet__y_n => 130 ,
        :last_transaction_code => 134 ,
        :last_transaction_date => 135 ,
        :list_office_code => 137 ,
        :list_date => 138 ,
        :list_agent_public_id => 143 ,
        :list_price => 144 ,
        :lot_sqft => 154 ,
        :community_name => 155 ,
        :ml_num => 163 ,
        :lo_name => 171 ,
        :original_list_price => 173 ,
        :photo_instructions => 182 ,
        :numden_other => 184 ,
        :property_condition => 202 ,
        :pvpool => 203 ,
        :record_delete_date => 205 ,
        :record_delete_flag => 207 ,
        :sale_price => 210 ,
        :buyer_broker => 211 ,
        :elementary_school_3_5 => 213 ,
        :high_school => 214 ,
        :jr_high_school => 215 ,
        :buyer_agent_public_id => 218 ,
        :sewer => 219 ,
        :numloft => 231 ,
        :sellers_contribution__ => 232 ,
        :sold_term => 233 ,
        :pvspa => 236 ,
        :approx_liv_area => 237 ,
        :status => 242 ,
        :subdivision_name => 247 ,
        :washer_dryer_location => 260 ,
        :water => 261 ,
        :year_built => 264 ,
        :zoning => 266 ,
        :property_description => 268 ,
        :garage_description => 269 ,
        :roof_description => 270 ,
        :lot_description => 271 ,
        :spa_description => 272 ,
        :pool_description => 273 ,
        :dining_room_description => 276 ,
        :family_room_description => 277 ,
        :kitchen_description => 278 ,
        :living_room_description => 279 ,
        :master_bath_desc => 280 ,
        :master_bedroom_description => 281 ,
        :second_bedroom_description => 282 ,
        :third_bedroom_description => 283 ,
        :fourth_bedroom_description => 284 ,
        :oven_description => 289 ,
        :other_appliance_description => 290 ,
        :construction_description => 291 ,
        :interior_description => 292 ,
        :flooring_description => 293 ,
        :fireplace_description => 294 ,
        :fence_type => 295 ,
        :equestrian_description => 296 ,
        :house_faces => 297 ,
        :miscellaneous_description => 298 ,
        :exterior_description => 299 ,
        :landscape_description => 300 ,
        :heating_description => 301 ,
        :heating_fuel_description => 302 ,
        :cooling_system => 303 ,
        :utility_information => 304 ,
        :energy_description => 305 ,
        :first_bedroom__1__1second_bath => 688 ,
        :first_bedroom_first_bath => 689 ,
        :first_bedroomsecond_bath => 690 ,
        :first_bedroom_rent => 692 ,
        :numfirst_bdrm_unfurn => 693 ,
        :second_bedroom_1_1_second_bath => 694 ,
        :second_bedroomfirst_bath => 695 ,
        :second_bedroom_second_bath => 696 ,
        :second_bedroom_rent => 698 ,
        :numsecond_bdrm_unfurn => 699 ,
        :third_bedroom_1_1second_bath => 700 ,
        :third_bedroomfirst_bath => 701 ,
        :third_bedroomsecond_bath => 702 ,
        :third_bedroom_rent => 704 ,
        :numthird_bdrm_unfurn => 705 ,
        :building_description => 732 ,
        :built_description => 735 ,
        :contingency_desc => 748 ,
        :cost_per_unit => 750 ,
        :flood_zone => 759 ,
        :handicap_adapted => 770 ,
        :heating_fuel_description => 771 ,
        :internet__y_n => 773 ,
        :maintenance => 782 ,
        :style => 1575 ,
        :building_description => 1576 ,
        :pool_description => 1578 ,
        :din_fam_room_description => 1579 ,
        :spa_description => 1580 ,
        :deposit => 1581 ,
        :lease_description => 1582 ,
        :tenant_pays => 1583 ,
        :directions => 1584 ,
        :other_appliance_description => 1586 ,
        :interior_description => 1587 ,
        :master_bedroom_description => 1588 ,
        :living_room_description => 1589 ,
        :flooring_description => 1590 ,
        :kitchen_description => 1591 ,
        :exterior_description => 1592 ,
        :fireplace_description => 1593 ,
        :fence_type => 1596 ,
        :heating_description => 1597 ,
        :heating_fuel_description => 1598 ,
        :cooling_description => 1599 ,
        :sold_lease_description => 1601 ,
        :est_clo_lse_dt => 1736 ,
        :lp_sqft__w_cents_ => 1738 ,
        :furnished => 1748 ,
        :idx => 1809 ,
        :virtual_tour_link => 2139 ,
        :sp_sqft => 2140 ,
        :photo_inst => 2146 ,
        :last_image_trans_date => 2238 ,
        :lp_sqft => 2341 ,
        :metro_map_coor_xp => 2343 ,
        :metro_map_page_xp => 2345 ,
        :subdivision_name_xp => 2353 ,
        :sp_sqft__w_cents_ => 2359 ,
        :sqft => 2361 ,
        :short_sale => 2369 ,
        :elementary_school_k_2 => 2377 ,
        :bedrooms__total_possible_num_ => 2379 ,
        :days_from_listing_to_close => 2381 ,
        :unitnumber => 2386 ,
        :assoc_comm_features_desc => 2388 ,
        :bath_downstairs__y_n => 2392 ,
        :bedroom_downstairs__y_n => 2394 ,
        :bldg_desc => 2414 ,
        :fireplace_location => 2422 ,
        :foreclosure_commenced_y_n => 2424 ,
        :furnishings_description => 2426 ,
        :great_room_y_n => 2428 ,
        :great_room_dimensions => 2430 ,
        :great_room_description => 2432 ,
        :parking_description => 2438 ,
        :washer_included_ => 2440 ,
        :dryer_included_ => 2442 ,
        :house_views => 2450 ,
        :property_subtype => 2452 ,
        :lot_square_foot => 2515 ,
        :num_acres => 2529 ,
        :seller_contribution => 2545 ,
        :condo_conversion_y_n  => 2549 ,
        :loft_dim_1st_floor  => 2555 ,
        :fifth_bedroom_description  => 2564 ,
        :fourth_bedroom_description  => 2566 ,
        :loft_dim_second_floor  => 2567 ,
        :bath_down_y_n  => 2569 ,
        :loft_description => 2570 ,
        :third_bedroom_description => 2571 ,
        :building_num => 2572 ,
        :unit_description => 2574 ,
        :approx_addl_liv_area => 2576 ,
        :bath_down_description => 2579 ,
        :den_dimensions => 2580 ,
        :fourth_bedroom_dimensions => 2584 ,
        :fifth_bedroom_dimensions => 2585 ,
        :third_bedroom_dimensions => 2586 ,
        :second_bedroom_dimensions => 2587 ,
        :second_bedroom_description => 2588 ,
        :master_bath_description => 2590 ,
        :furnished_description => 2591 ,
        :numden_other => 2592 ,
        :numloft => 2593 ,
        :lot_square_footage => 2594 ,
        :property_description => 2595 ,
        :family_room_dimensions => 2597 ,
        :great_room_dimensions => 2598 ,
        :great_room_y_n => 2599 ,
        :great_room_description => 2600 ,
        :dining_room_dimensions => 2601 ,
        :dining_room_description => 2602,
        :utility_information => 2604,
        :rent_range => 2607,
        :master_bedroom_dimensions => 2615,
        :garage_desc => 2616,
        :manufactured => 2617,
        :loft_dimensions => 2618,
        :family_room_description => 2622,
        :living_room_dimensions => 2623,
        :elem_3_5 => 2625,
        :converted_garage_y_n => 2627,
        :ladom => 2655,
        :bedroom_downstairs__y_n => 2657,
        :repo_reo_y_n => 2660,
        :building_number => 2664,
        :total_floors => 2665,
        :elevator_floor_num => 2667,
        :builder => 2668,
        :model => 2669,
        :built_description => 2670,
        :location => 2671,
        :tower_name => 2672,
        :association_features_available => 2677,
        :elementary_school_3_5 => 2678,
        :elementary_school_k_2 => 2679,
        :high_school => 2680,
        :jr_high_school => 2681,
        :metro_map_coor => 2683,
        :metro_map_page => 2684,
        :building_description => 2685,
        :unit_levels => 2686,
        :junior_suite__under_600_sqft_ => 2687,
        :full_baths => 2688,
        :three_quarter_baths => 2689,
        :baths_total => 2690,
        :half_baths => 2691,
        :unit_description => 2692,
        :condo_conversion => 2693,
        :approx_liv_area => 2694,
        :numden_other => 2695,
        :private_pool => 2696,
        :unit_pool_indoor => 2697,
        :private_spa => 2698,
        :unit_spa_indoor => 2699,
        :num_of_loft_areas => 2700,
        :parking_description => 2701,
        :num_of_parking_spaces_included => 2702,
        :parking_level => 2703,
        :directions => 2705,
        :living_room_description => 2708,
        :living_room_dimensions => 2709,
        :great_room_description => 2710,
        :great_room_dimensions => 2711,
        :media_room_y_n => 2712,
        :media_room_dimensions => 2713,
        :dining_room_description => 2714,
        :dining_room_dimensions => 2715,
        :kitchen_description => 2716,
        :kitchen_flooring => 2717,
        :kitchen_countertops => 2718,
        :master_bedroom_description => 2719,
        :master_bedroom_dimensions => 2720,
        :master_bath_description => 2721,
        :second_bedroom_description => 2722,
        :second_bedroom_dimensions => 2723,
        :third_bedroom_description => 2724,
        :third_bedroom_dimensions => 2725,
        :fourth_bedroom_description => 2726,
        :fourth_bedroom_dimensions => 2727,
        :fifth_bedroom_description => 2728,
        :fifth_bedroom_dimensions => 2729,
        :den_other_dimensions => 2730,
        :loft_area_dimensions => 2731,
        :loft_dimensions_1st_floor => 2732,
        :loft_dimensions_second_floor => 2733,
        :loft_description => 2734,
        :furnishings_description => 2735,
        :num_terraces => 2736,
        :terrace_total_sqft => 2737,
        :terrace_location => 2738,
        :refrigerator_included => 2739,
        :refrigerator_description => 2740,
        :disposal_included => 2741,
        :washer_included => 2742,
        :dryer_included => 2743,
        :dryer_utilities => 2744,
        :washer_dryer_location => 2745,
        :washer_dryer_description => 2746,
        :dishwasher_included => 2747,
        :dishwasher_description => 2748,
        :other_appliances => 2749,
        :oven_description => 2750,
        :interior => 2751,
        :flooring => 2752,
        :fireplace => 2753,
        :fireplace_description => 2754,
        :fireplace_location => 2755,
        :primary_view_direction => 2756,
        :views => 2757,
        :exterior_unit_description => 2758,
        :heating_description => 2760,
        :heating_fuel => 2761,
        :cooling_fuel => 2763,
        :cooling_system => 2764,
        :energy_description => 2765,
        :utility_information => 2766,
        :leed_certified => 2768,
        :num_storage_units => 2769,
        :storage_unit_desc => 2770,
        :on_site_staff_includes => 2775,
        :services_available_on_site => 2776,
        :security => 2777,
        :assoc_fee_includes => 2787,
        :foreclosure_commenced_y_n => 2804,
        :financing_considered => 2806,
        :possession_description => 2807,
        :internet__y_n => 2810,
        :lo_name => 2813,
        :power_on_or_off => 2826,
        :contingency_desc => 2829,
        :sellers_contribution__ => 2830,
        :property_condition => 2832,
        :subdivision_name => 2836,
        :foreclosure_commenced_y_n => 2837,
        :repo_reo_y_n => 2838,
        :great_room_y_n => 2840,
        :repo_reo_y_n => 2843,
        :public_address_y_n => 2858,
        :commentaryy_n => 2859,
        :avm_y_n => 2860,
        :public_address => 2861,
        :sp_lp => 2864,
        :auction_date => 2878,
        :auction_type => 2879,
        :buyer_premium => 2880,
        :drivinglatitude => 2901,
        :drivinglongitude => 2902,
        :city => 2909
      }
    end
    ################## Depricated Keys ##############################
    # => :partial_flag => "17",  #Integer
    # => :den_dim => "2511",                 #String
    # => :unit_desc => "2543",               #String
    # => :annual_property_tax => "28",       #Integer
    # => :association_fee => "39",           #Integer
    # => :initial_encumber_desc => "43",     #String
    # => :land_use => "132",                 #Integer
    # => :agent_member_id => "145",          #String
    # => :occupancy_desc => "170",           #String
    # => :listing_office_phone => "172",     #String
    # => :parcel_number => "176",            #String
    # => :street_name => "243",              #String
    # => :street_number => "244",            #String
    # => :original_price_sqft => "1740",     #Integer
    # => :xp_unit_number => "2363",          #String
    # => :ground_mounted? => "125",          #Boolean
    #- RES #:year_round_school => "216",  #String
    #- RES # :seller_contribution_amount => "232",  #Float
    #- RES #:style_desc => "257",         #String
    #- RES #:unit_number => "258",        #String
    #- RES #:directions => "274",         #String
    
    
    
    # Take values like true and false, convert them to "Y" or "N". make collections into joint strings.
    def value_map(value)
      v = case value.class
      when Array
        value.join(',')
      when Range
        "#{value.first}-#{value.last}"
      when Hash
        if value.has_key?(:or)
          "|#{value[:or].join(',')}"
        elsif value.has_key?(:not)
          "~#{value[:not].join(',')}"
        end
      when TrueClass
        "Y" # TODO: figure out if this should be Y or Yes
      when FalseClass
        "N" # TODO: figure out if this should be N or No
      else
        value
      end
      v
    end
    
  end
end